services:
    db:
        image: postgres
        container_name: postgres
        volumes:
            - mockdb_data:/var/lib/postgresql/data
            - ./db:/db
        restart: always
        environment:
            POSTGRES_USER: mockdb_user
            POSTGRES_PASSWORD: mockdb_password
            POSTGRES_DB: mockdb
        ports:
            - "5432:5432"

    dbmate:
        image: amacneil/dbmate:latest
        container_name: dbmate
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://mockdb_user:mockdb_password@db:5432/mockdb?sslmode=disable
            DBMATE_MIGRATIONS_DIR: /db/migrations
        volumes:
            - ./db:/db
        working_dir: /db
        entrypoint: ["dbmate"]

volumes:
    mockdb_data:
